<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
type Status = 'PROCESSED' | 'DUPLICATE' | 'REJECTED';
type Delivery = { id:number; eventId:string|null; status:Status; reason:string; sourceIp:string; bodySha256:string; keyVersion:string|null; receivedAt:string };
const events = ref<Delivery[]>([]); const loading = ref(true); const online = ref(true); const filter = ref<'ALL'|Status>('ALL');
const visible = computed(() => filter.value === 'ALL' ? events.value : events.value.filter(e => e.status === filter.value));
const counts = computed(() => ({ processed: events.value.filter(e=>e.status==='PROCESSED').length, duplicate: events.value.filter(e=>e.status==='DUPLICATE').length, rejected: events.value.filter(e=>e.status==='REJECTED').length }));
async function load(){loading.value=true;try{const r=await fetch('/api/events');if(!r.ok)throw new Error();events.value=await r.json();online.value=true}catch{online.value=false}finally{loading.value=false}}
onMounted(load);
</script>
<template><main>
  <nav><a class="brand"><span>IF</span> Integration Forensics</a><div class="nav-meta"><i :class="{off:!online}"></i>{{online?'receiver online':'api offline'}}<b>02 / 03</b></div></nav>
  <header class="hero"><div><p class="eyebrow">WEBHOOK INTAKE / HMAC-SHA256</p><h1>Every delivery<br><em>leaves evidence.</em></h1><p>Verify the raw bytes. Reject replays. Process each event once. Keep an audit trail for everything—including failures.</p></div><div class="shield"><div class="ring"><span>HMAC</span><b>256</b></div><p><i></i> signature binds timestamp + raw body</p></div></header>
  <section class="metrics"><article><span>ACCEPTED</span><b>{{counts.processed.toString().padStart(2,'0')}}</b><small>unique events processed</small></article><article><span>DUPLICATE</span><b>{{counts.duplicate.toString().padStart(2,'0')}}</b><small>acknowledged, not replayed</small></article><article><span>REJECTED</span><b>{{counts.rejected.toString().padStart(2,'0')}}</b><small>audit record preserved</small></article><article class="window"><span>REPLAY WINDOW</span><b>05:00</b><small>absolute timestamp distance</small></article></section>
  <section class="protocol"><div><p class="eyebrow">VERIFICATION PIPELINE</p><h2>Four gates. One business effect.</h2></div><ol><li><b>01</b><div><strong>Envelope</strong><small>event ID · timestamp · signature</small></div></li><li><b>02</b><div><strong>Freshness</strong><small>± 5 minute acceptance window</small></div></li><li><b>03</b><div><strong>Authenticity</strong><small>constant-time active/previous key check</small></div></li><li><b>04</b><div><strong>Idempotency</strong><small>unique event ID before side effect</small></div></li></ol></section>
  <section class="ledger"><header><div><p class="eyebrow">DELIVERY LEDGER</p><h2>Recent attempts</h2></div><div class="controls"><button v-for="item in ['ALL','PROCESSED','DUPLICATE','REJECTED']" :class="{active:filter===item}" @click="filter=item as typeof filter">{{item}}</button><button class="refresh" @click="load">↻ refresh</button></div></header><div class="table"><div class="table-head"><span>TIME / EVENT</span><span>DECISION</span><span>SOURCE</span><span>BODY DIGEST</span></div><div v-if="!loading && !visible.length" class="empty"><b>{{online?'No deliveries recorded yet.':'Receiver API is not running.'}}</b><small>{{online?'Run scripts/send-webhook.ps1 to create a signed delivery.':'Start the backend and MySQL, then refresh this ledger.'}}</small></div><article v-for="event in visible" :key="event.id"><div><time>{{new Date(event.receivedAt).toLocaleTimeString()}}</time><b>{{event.eventId||'missing-event-id'}}</b></div><span class="badge" :class="event.status.toLowerCase()">{{event.status}}</span><code>{{event.sourceIp}}</code><code>{{event.bodySha256.slice(0,18)}}…</code></article></div></section>
  <section class="failure"><div><p class="eyebrow">ATTACK / FAILURE MATRIX</p><h2>Failure is data,<br>not a dead end.</h2></div><div class="cases"><article><span>401</span><h3>Signature mismatch</h3><p>Raw bytes changed, the wrong secret signed them, or the signature header is absent.</p></article><article><span>401</span><h3>Expired timestamp</h3><p>A valid old request is still a replay. Freshness is checked before business processing.</p></article><article><span>200</span><h3>Duplicate event ID</h3><p>Return success to stop provider retries, record the attempt, skip the side effect.</p></article><article><span>ROTATE</span><h3>Previous key match</h3><p>Accept both keys during a bounded migration, then remove the old secret.</p></article></div></section>
  <footer><span>SPRING BOOT · MYSQL · CONSTANT-TIME HMAC</span><span>Payloads are represented by SHA-256 digests in the ledger.</span></footer>
</main></template>
